
development:
  adapter: postgresql
  encoding: unicode
  database: timetracker_development
  pool: 5
  username: postgres
  password: 12345
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: timetracker_test
  pool: 5
  username: postgres
  password: 12345
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: timetracker_production
  pool: 5
  password: 12345
  host: localhost
  port: 5432
